apiVersion: operator.openshift.io/v1alpha1
kind: ClusterAPI
metadata:
  name: cluster
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    exclude.release.openshift.io/internal-openshift-hosted: "true"
    release.openshift.io/feature-set: "CustomNoUpgrade,TechPreviewNoUpgrade"
    release.openshift.io/create-only: "true"
