apiVersion: operator.cluster.x-k8s.io/v1alpha1
kind: InfrastructureProvider
metadata:
  creationTimestamp: null
  name: ibmcloud
  namespace: openshift-cluster-api
spec:
  deployment:
    containers:
    - command:
      - ./bin/cluster-api-provider-ibmcloud-controller-manager
      name: manager
  fetchConfig:
    selector:
      matchLabels:
        provider.cluster.x-k8s.io/name: ibmcloud
        provider.cluster.x-k8s.io/type: infrastructure
  version: v0.5.1
status: {}
