apiVersion: operator.cluster.x-k8s.io/v1alpha1
kind: InfrastructureProvider
metadata:
  creationTimestamp: null
  name: aws
  namespace: openshift-cluster-api
spec:
  deployment:
    containers:
    - command:
      - ./bin/cluster-api-provider-aws-controller-manager
      name: manager
  fetchConfig:
    selector:
      matchLabels:
        provider.cluster.x-k8s.io/name: aws
        provider.cluster.x-k8s.io/type: infrastructure
  version: v2.2.0
status: {}
