apiVersion: operator.cluster.x-k8s.io/v1alpha1
kind: CoreProvider
metadata:
  creationTimestamp: null
  name: cluster-api
  namespace: openshift-cluster-api
spec:
  deployment:
    containers:
    - command:
      - ./bin/cluster-api-controller-manager
      name: manager
  fetchConfig:
    selector:
      matchLabels:
        provider.cluster.x-k8s.io/name: cluster-api
        provider.cluster.x-k8s.io/type: core
  version: v1.4.2
status: {}
